org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=Bryce
plugin_description=A mod which contains some tools to help you make mob farms!
plugin_author=Bryce
plugin_website=
plugin_main_entrypoint=com.bryce.mobfarmtools.MobFarmingToolsPlugin
server_version=*
